language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - SCRIPT=platformioSingle EXAMPLE_NAME=UserData EXAMPLE_FOLDER=/ BOARDTYPE=esp8266 BOARD=d1_mini
    - SCRIPT=platformioSingle EXAMPLE_NAME=UserData EXAMPLE_FOLDER=/ BOARDTYPE=esp32 BOARD=lolin32


install:
    - pip install -U platformio
    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/561/JsonStreamingParser
    - platformio lib -g install 561

script: scripts/travis/$SCRIPT.sh
